name: JobsAddons
main: net.lumamc.jobsaddons.JobsAddons
version: '${version}'
depend:
  - LumaCore
  - LuckPerms
  - Jobs
  - PlaceholderAPI
softdepend:
  - WorldGuard
  - EvenMoreFish
  - Vault
api-version: 1.21
author: Jsinco