name: JobsAddons
main: net.lumamc.jobsaddons.JobsAddons
version: '${version}'
depend:
  - LumaCore
  - LuckPerms
  - Jobs
softdepend:
  - WorldGuard
  - LumaItems
  - SafariNet
  - EvenMoreFish
api-version: 1.21
author: Jsinco